Hospice\SiteBundle\Entity\Event:
        type: entity
        table: event
        id:
            id:
                type: integer
                generator: { strategy: AUTO }
        fields:
            type:
                  type: integer
            name:
                  type: string
                  length: 255
                  nullable: true
            description:
                  type: string
                  length: 255
                  nullable: true
            start:
                  type: datetime
                  nullable: true
            end:
                  type: datetime
                  nullable: true
        uniqueConstraints:
            event_idx:
                columns: [ id ]


