Hospice\SiteBundle\Entity\EventCategory:
        type: entity
        table: event_category
        id:
            id:
                type: integer
                generator: { strategy: AUTO }
        fields:
            name:
                  type: string
                  length: 50
                  nullable: false
        uniqueConstraints:
            event_category_idx:
                columns: [ id]
            event_category_name:
                columns: [ name ]


