Hospice\SiteBundle\Entity\Event:
        type: entity
        repositoryClass: Hospice\SiteBundle\Entity\EventRepository
        table: event
        id:
            id:
                type: integer
                generator: { strategy: AUTO }
        fields:
            name:
                  type: string
                  length: 255
                  nullable: true
            description:
                  type: string
                  length: 255
                  nullable: true
            start:
                  type: datetime
                  nullable: true
            end:
                  type: datetime
                  nullable: true
        manyToMany:
            patients:
                targetEntity: Patient
                mappedBy: events
            volunteers:
                targetEntity: Volunteer
                mappedBy: events

        manyToOne:
            type: 
                targetEntity: EventCategory
        oneToOne:
            recurOptions:
                targetEntity: EventRecur
                mappedBy: event
        uniqueConstraints:
            event_idx:
                columns: [ id ]


