Hospice\SiteBundle\Entity\IntervalOption:
        type: entity
        table: interval_option
        id:
            id:
                type: integer
                generator: { strategy: AUTO }
        fields:
            name:
                  type: string
                  length: 50
                  nullable: false
            value:
                type: integer
        manyToOne:
            frequency:
                targetEntity: Frequency

        uniqueConstraints:
            interval_options_idx:
                columns: [ id ]
            interval_options_name:
                columns: [ name ]


