Hospice\SiteBundle\Entity\Patient:
        type: entity
        table: patient
        id:
            id:
                type: integer
                generator: { strategy: AUTO }
        fields:
            pesel:
                  type: string
                  length: 11
            name:
                  type: string
                  length: 255
            lastname:
                  type: string
                  length: 255
            address:
                  type: string
                  length: 100
            age:  
                  type: integer
        uniqueConstraints:
            patient_idx:
                columns: [ id ]
        manyToMany:
            events:
                targetEntity: Event
                joinTable:
                    name: event_patient
                    joinColumns:
                        event_id:
                            referencedColumnName: id
                    inverseJoinColumns:
                        patient_id:
                            referencedColumnName: id
